apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckds-ml-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckds-ml-app
  template:
    metadata:
      labels:
        app: ckds-ml-app
    spec:
      containers:
      - name: ckds-ml-app
        image: gcr.io/ckdkubernetesgcp/ckds_ml_app
        ports:
        - containerPort: 8080  # Change to 8080 if that is your app's listening port
